from django.urls import path
# from Pronto360.Pronto_Home.views import detailcarousel_2, err_404, listingmap
from Pronto_Home import views

urlpatterns = [
    path('', views.index, name='home'),
    path('services/', views.services, name='services'),
    path('electrician/', views.services, name='electrician'),
    path('plumbing/', views.services, name='plumbing'),
    path('handyman/', views.services, name='handyman'),
    path('roofing/', views.services, name='roofing'),
    path('HVAC/', views.services, name='HVAC'),
    path('carpenter/', views.services, name='carpenter'),
    path('other/', views.services, name='other'),
    path('blog/', views.blog, name='blog'),
    path('account/', views.account, name='account'),
    path('help/', views.help, name='help'),
    path('faq/', views.faq, name='faq'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('add_listing/', views.account, name='add_listing'),
    path('detail-restaurant/', views.detail_restaurant, name='detail-restaurant'),
    path('media-gallery/', views.media_gallery, name='media_gallery'),
    path('checkout/', views.checkout, name='checkout'),
    path('sidebar-search/', views.sidebarsearch, name='sidebar_search'),
    path('full-search/', views.fullsearch, name='full_search'),
    path('full-isotope/', views.fullisotope, name = 'full-isotope'),
    path('listing-map/', views.listingmap, name='listing_map'),
    path('confirm/', views.confirm, name='confirm'),
    path('bookings/', views.bookings, name = 'bookings'),
    path('detail-hotel/', views.detail_hotel, name='detail-hotel'),
    path('detail-shop/', views.detail_shop, name = 'detail-shop'),
    path('detail-carousel/', views.detailcarousel, name='detail-carousel'),
    path('detail-carousel-2/', views.detailcarousel_2, name='detail-carousel-2'),
    path('error-404/', views.err_404, name='404'),
    path('contacts-2/', views.contacts2, name='contacts_2'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('menu-options', views.menu_options, name='menu_options'),
    path('invoice', views.invoice, name='invoice'),
]
